Resolved issues and added new features.
zoni-group/games pull request #61
Opened 2024-09-10 17:29 UTC by AbhishekBante

This PR implements:
1. Disable Submit Button Until Participant either select at least 2 answers for check choice type of answers or enter some text input.
2. Resized media to cover specific portion only and not whole screen. This resolves the button hiding due to media overflowing.
3. Commented the block of code that updates the case sensitivity flag to false even when it was true.
4. Increased the font size of options.
5. Moved your position info on top of leaderboard.

2024-09-11 21:48 UTC, opereztuta requested changes
@AbhishekBante, it's a good practice to create separate PRs for bug fixes and new features to keep the changes focused and easier to review.

For bug fixes, please include clear steps to reproduce the issue, along with a detailed explanation of the root cause and how your changes address the problem. In this case, the capitalization issue isn't entirely clear to me—could you provide more context or clarification?

2024-09-11 21:48 UTC, opereztuta commented on frontend/src/lib/editor/TextEditorPart.svelte
> +	// for (let i = 0; i < data.questions[selected_question].answers.length; i++) {
@AbhishekBante what's the reason to remove to comment this block of code?

2024-09-11 21:48 UTC, opereztuta commented on frontend/src/lib/play/question.svelte
> +								<p class="m-auto button-text text-sm text-[#fff] dark:text-[#fff] sm:text-base md:text-lg lg:text-xl">{answer.answer}</p>
@AbhishekBante, I see you are removing the getTextColor function. This function was added to ensure a good contrast between the text and the background. The system allows users to customize answers' backgrounds. My suggestion is to keep this functionality.

2024-09-12 14:21 UTC, AbhishekBante commented on frontend/src/lib/editor/TextEditorPart.svelte
> +	// for (let i = 0; i < data.questions[selected_question].answers.length; i++) {
Addressing the issue,
To reproduce the issue here are the steps:
1. Create a new game with only text questions in it.
2. The options of text questions should be ticked case sensitive.
3. After saving the game edit the same game again.
4. while exploring the questions you will see that the case sensitivity is unticked even when we ticked it.

This was the issue addressed by Maria S.

I took a look at the code and found out this loop is by default flagging the case_sensitivy coming from database to false.
Therefore I commented this loop to solve the issue. Also this block of code seem unnecessary that's also the reason I commented it.

Please let me know if this is wrong.

2024-09-12 14:55 UTC, AbhishekBante commented on frontend/src/lib/play/question.svelte
> +								<p class="m-auto button-text text-sm text-[#fff] dark:text-[#fff] sm:text-base md:text-lg lg:text-xl">{answer.answer}</p>
I removed the getTextColor function because in some options the text color was black and in some it was white which was looking weird, but your is valid too should I reset it back as it was?

2024-09-12 19:31 UTC, closed without merging